name: Main

# When new commits are pushed to 'main' or when a pull request is opened against 'main'
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build :
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: 'stable'

      - name: Install pub dependencies
        run: flutter pub get

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
            sudo apt-get update -y
            sudo apt-get install -y ninja-build libgtk-3-dev

      - name: Build Windows
        if: runner.os == 'Windows'
        run: flutter build windows --release

      - name: Build macOS
        if: runner.os == 'macOS'
        run: flutter build macos --release

      - name: Build Linux
        if: runner.os == 'Linux'
        run: flutter build linux --release

      - name: Upload Windows Artifact
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: release-build-Windows
          path: build/windows/runner/Release

      - name: Upload macOS Artifact
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: release-build-macOS
          path: build/macos/Build/Products/Release/*.app

      - name: Upload Linux Artifact
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: release-build-Linux
          path: build/linux/x64/release/bundle/*
